ported ibex and ri5cy
tests compile - haven't run them

diff --git a/riscv-target/ibex/device/rv32imc/Makefile.include b/riscv-target/ibex/device/rv32imc/Makefile.include
--- a/riscv-target/ibex/device/rv32imc/Makefile.include
+++ b/riscv-target/ibex/device/rv32imc/Makefile.include
@@ -1,4 +1,4 @@
-IBEX        = $(ROOTDIR)/riscv-target/ibex/device/rv32imc
+IBEX        = $(TARGETDIR)/ibex/device/rv32imc
 LDSCRIPT    = $(IBEX)/link.ld
 TRAPHANDLER = $(IBEX)/handler.S
 DEFINES     = -DPRIV_MISA_S=0 -DPRIV_MISA_U=0 -DTRAPHANDLER="\"$(TRAPHANDLER)\""
@@ -20,17 +20,32 @@ RISCV_GCC      ?= $(RISCV_PREFIX)gcc
 RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
 RISCV_OBJCOPY  ?= $(RISCV_PREFIX)objcopy
 RISCV_READELF  ?= $(RISCV_PREFIX)readelf
-RISCV_GCC_OPTS ?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles
+RISCV_GCC_OPTS ?= -g -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles $(RVTEST_DEFINES) $(DEFINES)
+
+COMPILE_CMD = $$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
+							-I$(ROOTDIR)/riscv-test-suite/env/ \
+							-I$(TARGETDIR)/$(RISCV_TARGET)/ \
+							-T$(LDSCRIPT) \
+							$$(<) -o $$@ 
+
+OBJ_CMD = $$(RISCV_OBJDUMP) $$@ -D > $$@.objdump; \
+					$$(RISCV_OBJDUMP) $$@ --source > $$@.debug; \
+    			$$(RISCV_READELF) -a $$(@) > $$(@).readelf; \
+    			$$(RISCV_OBJCOPY) -O binary $$(@) $$(@).bin; \
+    			srec_cat $$(@).bin -binary -offset 0x0000 -byte-swap 4 -o $$(@).vmem -vmem    
+
 
 COMPILE_TARGET=\
-	$$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
-		-I$(ROOTDIR)/riscv-test-env/ \
-		-I$(ROOTDIR)/riscv-test-env/p/ \
-		-I$(TARGETDIR)/$(RISCV_TARGET)/ \
-		$(DEFINES) -T$(LDSCRIPT) $$(<) \
-		-o $$(@); \
-    $$(RISCV_OBJDUMP) -D $$(@) > $$(@).objdump; \
-    $$(RISCV_READELF) -a $$(@) > $$(@).readelf; \
-    $$(RISCV_OBJCOPY) -O binary $$(@) $$(@).bin; \
-    srec_cat $$(@).bin -binary -offset 0x0000 -byte-swap 4 -o $$(@).vmem -vmem    
-    
+				$(COMPILE_CMD); \
+        if [ $$$$? -ne 0 ] ; \
+                then \
+                echo "\e[31m$$(RISCV_GCC) failed for target $$(@) \e[39m" ; \
+                exit 1 ; \
+                fi ; \
+				$(OBJ_CMD); \
+        if [ $$$$? -ne 0 ] ; \
+                then \
+                echo "\e[31m $$(RISCV_OBJDUMP) failed for target $$(@) \e[39m" ; \
+                exit 1 ; \
+                fi ;
+
diff --git a/riscv-target/ri5cy/device/rv32imc/Makefile.include b/riscv-target/ri5cy/device/rv32imc/Makefile.include
--- a/riscv-target/ri5cy/device/rv32imc/Makefile.include
+++ b/riscv-target/ri5cy/device/rv32imc/Makefile.include
@@ -1,4 +1,4 @@
-RI5CY       = $(ROOTDIR)/riscv-target/ri5cy/device/rv32imc
+RI5CY       = $(TARGETDIR)/ri5cy/device/rv32imc
 LDSCRIPT    = $(RI5CY)/link.ld
 TRAPHANDLER = $(RI5CY)/handler.S
 DEFINES     = -DPRIV_MISA_S=0 -DPRIV_MISA_U=0 -DTRAPHANDLER="\"$(TRAPHANDLER)\""
@@ -18,16 +18,32 @@ RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
 RISCV_OBJCOPY  ?= $(RISCV_PREFIX)objcopy
 RISCV_NM       ?= $(RISCV_PREFIX)nm
 RISCV_READELF  ?= $(RISCV_PREFIX)readelf
-RISCV_GCC_OPTS ?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles $(RVTEST_DEFINES)
+RISCV_GCC_OPTS ?= -g -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles $(RVTEST_DEFINES) $(DEFINES)
+
+COMPILE_CMD = $$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
+							-I$(ROOTDIR)/riscv-test-suite/env/ \
+		-I$(TARGETDIR)/$(RISCV_TARGET)/ \
+							-T$(LDSCRIPT) \
+							$$(<) -o $$@ 
+
+OBJ_CMD = $$(RISCV_OBJDUMP) $$@ -D > $$@.objdump; \
+					$$(RISCV_OBJDUMP) $$@ --source > $$@.debug; \
+    			$$(RISCV_READELF) -a $$(@) > $$(@).readelf; \
+    			$$(RISCV_OBJCOPY) -O binary $$(@) $$(@).bin; \
+    			srec_cat $$(@).bin -binary -offset 0x0000 -byte-swap 4 -o $$(@).vmem -vmem    
+
 
 COMPILE_TARGET=\
-	$$(RISCV_GCC) $(2) $$(RISCV_GCC_OPTS) \
-		-I$(ROOTDIR)/riscv-test-env/ \
-		-I$(ROOTDIR)/riscv-test-env/p/ \
-		-I$(TARGETDIR)/$(RISCV_TARGET)/ \
-		$(DEFINES) -T$(LDSCRIPT) $$< \
-		-o $(work_dir_isa)/$$@; \
-    $$(RISCV_OBJDUMP) -D $(work_dir_isa)/$$@ > $(work_dir_isa)/$$@.objdump; \
-    $$(RISCV_READELF) -a $(work_dir_isa)/$$@ > $(work_dir_isa)/$$@.readelf; \
-    $$(RISCV_NM) $(work_dir_isa)/$$@ > $(work_dir_isa)/$$@.nm; \
-    $$(RISCV_OBJCOPY) -O verilog $(work_dir_isa)/$$@ $(work_dir_isa)/$$@.bin;
+				$(COMPILE_CMD); \
+        if [ $$$$? -ne 0 ] ; \
+                then \
+                echo "\e[31m$$(RISCV_GCC) failed for target $$(@) \e[39m" ; \
+                exit 1 ; \
+                fi ; \
+				$(OBJ_CMD); \
+        if [ $$$$? -ne 0 ] ; \
+                then \
+                echo "\e[31m $$(RISCV_OBJDUMP) failed for target $$(@) \e[39m" ; \
+                exit 1 ; \
+                fi ;
+
